export const bar = {
    "type": "FeatureCollection",
    "name": "bar",
    "crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
    "features": [
        { "type": "Feature", "properties": { "name": "Black Swan", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5874331, 55.6864894] } },
        { "type": "Feature", "properties": { "name": "Krog's Fiskerestaurant", "wikidata": "Q21936680", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5785538, 55.6777413] } },
        { "type": "Feature", "properties": { "name": "Klods Hans", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.588872, 55.680579] } },
        { "type": "Feature", "properties": { "name": "Oak Room", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5582375, 55.6906627] } },
        { "type": "Feature", "properties": { "name": "Vang & Bar", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5420547, 55.6632191] } },
        { "type": "Feature", "properties": { "name": "Underwood Ink. II Bar", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5672552, 55.6920557] } },
        { "type": "Feature", "properties": { "name": "Fermentoren", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5563311, 55.6679616] } },
        { "type": "Feature", "properties": { "name": "Cafe 33", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5535148, 55.6660465] } },
        { "type": "Feature", "properties": { "name": "Elmo", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5471487, 55.6675901] } },
        { "type": "Feature", "properties": { "name": "Vesterbro Vinstue", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5497023, 55.6682661] } },
        { "type": "Feature", "properties": { "name": "Malbeck", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.553299, 55.6690546] } },
        { "type": "Feature", "properties": { "name": "Darling", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5466941, 55.6668622] } },
        { "type": "Feature", "properties": { "name": "Riesen", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5496981, 55.6692729] } },
        { "type": "Feature", "properties": { "name": "Cafè Guldhornene", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5693007, 55.6772854] } },
        { "type": "Feature", "properties": { "name": "Heidi's Bier Bar", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5694568, 55.6773855] } },
        { "type": "Feature", "properties": { "name": "The Australien Bar", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5705635, 55.6779133] } },
        { "type": "Feature", "properties": { "name": "La Boucherie", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5707085, 55.6779717] } },
        { "type": "Feature", "properties": { "name": "Trykbar", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5804369, 55.6822933] } },
        { "type": "Feature", "properties": { "name": "Bodega 54", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5565742, 55.668674] } },
        { "type": "Feature", "properties": { "name": "Freddys Bar", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5582526, 55.6696351] } },
        { "type": "Feature", "properties": { "name": "Lones Kro", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5584065, 55.6698539] } },
        { "type": "Feature", "properties": { "name": "Café Centralen", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5581224, 55.6697425] } },
        { "type": "Feature", "properties": { "name": "Hos Tove", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5580263, 55.6702253] } },
        { "type": "Feature", "properties": { "name": "Tjili Pop 2", "wikidata": "Q18552345", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5500587, 55.6864665] } },
        { "type": "Feature", "properties": { "name": "gilt", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5479826, 55.6870129] } },
        { "type": "Feature", "properties": { "name": "Barcelona", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5603015, 55.6898514] } },
        { "type": "Feature", "properties": { "name": "Holstein Bodega", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5812029, 55.6987309] } },
        { "type": "Feature", "properties": { "name": "Café Ludwigsen", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5436884, 55.6709507] } },
        { "type": "Feature", "properties": { "name": "Café Haraldsborg", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5780731, 55.6675771] } },
        { "type": "Feature", "properties": { "name": "Isbjørnen", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5785286, 55.6678361] } },
        { "type": "Feature", "properties": { "name": "Mikkeller Bar Viktoriagade", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5575483, 55.6719575] } },
        { "type": "Feature", "properties": { "name": "Cube", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5612145, 55.673194] } },
        { "type": "Feature", "properties": { "name": "Stempel Bar & Kitchen", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5477341, 55.6673995] } },
        { "type": "Feature", "properties": { "name": "Høllmers Bar", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5569385, 55.672966] } },
        { "type": "Feature", "properties": { "name": "Villa Vino", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5713541, 55.6764611] } },
        { "type": "Feature", "properties": { "name": "K Cocktailbar", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5807439, 55.6779554] } },
        { "type": "Feature", "properties": { "name": "Café Mønten", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5910624, 55.6789623] } },
        { "type": "Feature", "properties": { "name": "Gensyn Amager", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5945051, 55.6656209] } },
        { "type": "Feature", "properties": { "name": "The Old Irish Pub", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5662488, 55.6754915] } },
        { "type": "Feature", "properties": { "name": "Ocak Café", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5847075, 55.6821264] } },
        { "type": "Feature", "properties": { "name": "Natcafeen", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5842922, 55.6815566] } },
        { "type": "Feature", "properties": { "name": "Mælk", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5836617, 55.6817227] } },
        { "type": "Feature", "properties": { "name": "Koster", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5823968, 55.6821086] } },
        { "type": "Feature", "properties": { "name": "Andy's Bar", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5822351, 55.6821592] } },
        { "type": "Feature", "properties": { "name": "Cucaracha Bar", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5816691, 55.6823061] } },
        { "type": "Feature", "properties": { "name": "Basement", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5825764, 55.6818655] } },
        { "type": "Feature", "properties": { "name": "Jazz Café", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.582289, 55.6818706] } },
        { "type": "Feature", "properties": { "name": "LaBar", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5810346, 55.6812694] } },
        { "type": "Feature", "properties": { "name": "Vinbar", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5816422, 55.6810501] } },
        { "type": "Feature", "properties": { "name": "Cafe Rex", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5794331, 55.6812502] } },
        { "type": "Feature", "properties": { "name": "Bo-Bi Bar", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5786867, 55.6810096] } },
        { "type": "Feature", "properties": { "name": "Hornsleth", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5771236, 55.6805487] } },
        { "type": "Feature", "properties": { "name": "Den glade Gris", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5745981, 55.6800283] } },
        { "type": "Feature", "properties": { "name": "Lundgren V.I.P", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5546478, 55.6716843] } },
        { "type": "Feature", "properties": { "name": "Bubbles", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5789264, 55.7059235] } },
        { "type": "Feature", "properties": { "name": "VinBaren", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5444608, 55.6958705] } },
        { "type": "Feature", "properties": { "name": "Kassen", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5606456, 55.6880152] } },
        { "type": "Feature", "properties": { "name": "Harbo Bar", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5594632, 55.6876448] } },
        { "type": "Feature", "properties": { "name": "Halvandet", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.6095487, 55.6954525] } },
        { "type": "Feature", "properties": { "name": "Toga Vinstue", "wikidata": "Q16324763", "wikipedia": "da:Toga Vinstue" }, "geometry": { "type": "Point", "coordinates": [12.5803397, 55.6787751] } },
        { "type": "Feature", "properties": { "name": "Library Bar", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5646995, 55.6738595] } },
        { "type": "Feature", "properties": { "name": "Thai-Corner", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5576296, 55.6705967] } },
        { "type": "Feature", "properties": { "name": "Tagensborg", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5539607, 55.6991498] } },
        { "type": "Feature", "properties": { "name": "Fat Tuesday Bar", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.583869, 55.681091] } },
        { "type": "Feature", "properties": { "name": "Palæ Bar", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5837207, 55.6812131] } },
        { "type": "Feature", "properties": { "name": "Da Vinci", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5837032, 55.6817658] } },
        { "type": "Feature", "properties": { "name": "Dispensary", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5446162, 55.6972417] } },
        { "type": "Feature", "properties": { "name": "Masken Bar", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5686176, 55.6781756] } },
        { "type": "Feature", "properties": { "name": "The Log Lady", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.568967, 55.6783036] } },
        { "type": "Feature", "properties": { "name": "Retro Disco", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5711036, 55.6779345] } },
        { "type": "Feature", "properties": { "name": "Kongens Bar", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5842835, 55.6797103] } },
        { "type": "Feature", "properties": { "name": "Foster's", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.572308, 55.6751773] } },
        { "type": "Feature", "properties": { "name": "Icebar Copenhagen", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5731153, 55.6754919] } },
        { "type": "Feature", "properties": { "name": "Mojo Blues Bar", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5735337, 55.6756583] } },
        { "type": "Feature", "properties": { "name": "Wessels Kro", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.580734, 55.681166] } },
        { "type": "Feature", "properties": { "name": "R Vinbar", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5801525, 55.6819319] } },
        { "type": "Feature", "properties": { "name": "Surf Bar", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5746625, 55.6799727] } },
        { "type": "Feature", "properties": { "name": "Hong Kong", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5884807, 55.6806961] } },
        { "type": "Feature", "properties": { "name": "The Barking Dog", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5624942, 55.6901037] } },
        { "type": "Feature", "properties": { "name": "Kind of Blue", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5624146, 55.6891027] } },
        { "type": "Feature", "properties": { "name": "Terroiristen", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5427877, 55.693679] } },
        { "type": "Feature", "properties": { "name": "Hatten Bar", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.590686, 55.6537296] } },
        { "type": "Feature", "properties": { "name": "Dupong", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5523945, 55.6859481] } },
        { "type": "Feature", "properties": { "name": "Ølsnedkeren", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5523274, 55.6858864] } },
        { "type": "Feature", "properties": { "name": "Bakken", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.559701, 55.6687256] } },
        { "type": "Feature", "properties": { "name": "Gorki", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5633186, 55.6818289] } },
        { "type": "Feature", "properties": { "name": "TAP10", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5776915, 55.7048999] } },
        { "type": "Feature", "properties": { "name": "X-pressen", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5786014, 55.7058942] } },
        { "type": "Feature", "properties": { "name": "Billy Booze", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5712944, 55.6771423] } },
        { "type": "Feature", "properties": { "name": "Global - World Music Venue", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5599114, 55.6914833] } },
        { "type": "Feature", "properties": { "name": "Mikkeller & Friends", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5432048, 55.6946671] } },
        { "type": "Feature", "properties": { "name": "Søernes Ølbar", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5750656, 55.6962633] } },
        { "type": "Feature", "properties": { "name": "Candeur - Dessert & Cocktail Bar", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5841806, 55.6812099] } },
        { "type": "Feature", "properties": { "name": "Kimia", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5596239, 55.687776] } },
        { "type": "Feature", "properties": { "name": "Bar O", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5813181, 55.6801699] } },
        { "type": "Feature", "properties": { "name": "Madam Chu's", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5784331, 55.6777292] } },
        { "type": "Feature", "properties": { "name": "The Jane", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5761475, 55.6801316] } },
        { "type": "Feature", "properties": { "name": "Ruby", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5766194, 55.6766934] } },
        { "type": "Feature", "properties": { "name": "The Standard", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5921381, 55.6779325] } },
        { "type": "Feature", "properties": { "name": "Holmens Kanal Cocktailbar", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5863873, 55.6783219] } },
        { "type": "Feature", "properties": { "name": "Floss", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5698566, 55.6781561] } },
        { "type": "Feature", "properties": { "name": "The Ballroom", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5738434, 55.7024728] } },
        { "type": "Feature", "properties": { "name": "Falernum", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5499759, 55.6740948] } },
        { "type": "Feature", "properties": { "name": "Kølsters Tolv Haner", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5469304, 55.6876177] } },
        { "type": "Feature", "properties": { "name": "Urban Bar", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5623557, 55.6721405] } },
        { "type": "Feature", "properties": { "name": "Klør Dame", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.551194, 55.701174] } },
        { "type": "Feature", "properties": { "name": "Det Lille Vinhus", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5865721, 55.6822531] } },
        { "type": "Feature", "properties": { "name": "Bæst", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5749273, 55.6793579] } },
        { "type": "Feature", "properties": { "name": "B9 Vinbar", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5562719, 55.6834105] } },
        { "type": "Feature", "properties": { "name": "Balderdash", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5777113, 55.6798954] } },
        { "type": "Feature", "properties": { "name": "The Bird and the Churchkey", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5780759, 55.6776418] } },
        { "type": "Feature", "properties": { "name": "Ravnsborg vinbar", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5626563, 55.689263] } },
        { "type": "Feature", "properties": { "name": "Bodega Tivoli Vinstue", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5669645, 55.6736143] } },
        { "type": "Feature", "properties": { "name": "Stubbens Cafe og Bar", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5268698, 55.6483192] } },
        { "type": "Feature", "properties": { "name": "Boulevard Bodega", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.597706, 55.6660178] } },
        { "type": "Feature", "properties": { "name": "Amager Bryghus Taproom Bryggen", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.578507, 55.665826] } },
        { "type": "Feature", "properties": { "name": "Hyggebar", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5760406, 55.6910254] } },
        { "type": "Feature", "properties": { "name": "Jacques D.", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5702372, 55.6878755] } },
        { "type": "Feature", "properties": { "name": "Tolv Haner", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5470834, 55.6875478] } },
        { "type": "Feature", "properties": { "name": "MadMad Mad Bodega", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5477451, 55.6721941] } },
        { "type": "Feature", "properties": { "name": "Gringo Bar", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5722433, 55.6787957] } },
        { "type": "Feature", "properties": { "name": "Kayak Bar", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.586764, 55.675205] } },
        { "type": "Feature", "properties": { "name": "Born 12\/ Jailhouse CPH", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5700342, 55.6788802] } },
        { "type": "Feature", "properties": { "name": "Nimb Bar", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5660687, 55.6736038] } },
        { "type": "Feature", "properties": { "name": "Den Vandrette Vinbar", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5924247, 55.6786438] } },
        { "type": "Feature", "properties": { "name": "Vinomatik", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.573863, 55.67926] } },
        { "type": "Feature", "properties": { "name": "Klør Bonde", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.586697, 55.704862] } },
        { "type": "Feature", "properties": { "name": "Hafnia bar", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5826042, 55.6817975] } },
        { "type": "Feature", "properties": { "name": "Lou Lou", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5830687, 55.6811399] } },
        { "type": "Feature", "properties": { "name": "Mimers Bodega", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5503495, 55.6983406] } },
        { "type": "Feature", "properties": { "name": "", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5448926, 55.6434567] } },
        { "type": "Feature", "properties": { "name": "El Cava", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5811954, 55.6775664] } },
        { "type": "Feature", "properties": { "name": "Dahl & Dahl", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5882248, 55.6834282] } },
        { "type": "Feature", "properties": { "name": "Nebbiolo Winebar", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5892433, 55.681141] } },
        { "type": "Feature", "properties": { "name": "La Fontaine", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.576151, 55.6773717] } },
        { "type": "Feature", "properties": { "name": "Strøm Bar", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5760558, 55.6801783] } },
        { "type": "Feature", "properties": { "name": "Studenterhuset", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5763426, 55.6811729] } },
        { "type": "Feature", "properties": { "name": "Barfly", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5712957, 55.6814402] } },
        { "type": "Feature", "properties": { "name": "Absurt", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.56764, 55.6846453] } },
        { "type": "Feature", "properties": { "name": "LuLu", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5621783, 55.6885594] } },
        { "type": "Feature", "properties": { "name": "Balthazar Champagne Bar", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5833472, 55.6805372] } },
        { "type": "Feature", "properties": { "name": "Kjær & Sommerfeldt", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.581666, 55.6811473] } },
        { "type": "Feature", "properties": { "name": "Ved Stranden 10", "wikidata": "Q28225883", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5815953, 55.677305] } },
        { "type": "Feature", "properties": { "name": "Vinskabet", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5599721, 55.68682] } },
        { "type": "Feature", "properties": { "name": "Alpehytten Biergarten I", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5668858, 55.6727762] } },
        { "type": "Feature", "properties": { "name": "Juize N booze", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5700264, 55.6779045] } },
        { "type": "Feature", "properties": { "name": "Imperial Bio Nedre Bar", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5611991, 55.6751958] } },
        { "type": "Feature", "properties": { "name": "44 Harbour Street Jazz Club", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5921765, 55.6779936] } },
        { "type": "Feature", "properties": { "name": "Hvitfeldt", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5735725, 55.6820512] } },
        { "type": "Feature", "properties": { "name": "Vinhanen", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5451787, 55.669432] } },
        { "type": "Feature", "properties": { "name": "Parken Bar 7", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5717639, 55.7033623] } },
        { "type": "Feature", "properties": { "name": "Brus", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5561981, 55.6921663] } },
        { "type": "Feature", "properties": { "name": "Cafe Stadion", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5610607, 55.6938765] } },
        { "type": "Feature", "properties": { "name": "Nimb Bar og Banquet 1. sal", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5661, 55.6735506] } },
        { "type": "Feature", "properties": { "name": "Hvepsereden", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.53982, 55.7009477] } },
        { "type": "Feature", "properties": { "name": "Vinhanen", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5594593, 55.6869467] } },
        { "type": "Feature", "properties": { "name": "Nyhavns Bodega", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.589734, 55.6807121] } },
        { "type": "Feature", "properties": { "name": "Café Olsen Banden", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.56366, 55.6765839] } },
        { "type": "Feature", "properties": { "name": "Imperial Bio Øvre Bar", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5612217, 55.6752253] } },
        { "type": "Feature", "properties": { "name": "Bar Jabobsen", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5798809, 55.6794569] } },
        { "type": "Feature", "properties": { "name": "Los", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5580127, 55.6917576] } },
        { "type": "Feature", "properties": { "name": "Café Casual", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5179276, 55.6665002] } },
        { "type": "Feature", "properties": { "name": "TH. Bar", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5154482, 55.6666377] } },
        { "type": "Feature", "properties": { "name": "Jacobsen", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5312504, 55.6647323] } },
        { "type": "Feature", "properties": { "name": "Vinbaren Vesterbro Torv", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.554793, 55.67167] } },
        { "type": "Feature", "properties": { "name": "Kocktails", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.549315, 55.687061] } },
        { "type": "Feature", "properties": { "name": "Portvinsbaren", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.545461, 55.671923] } },
        { "type": "Feature", "properties": { "name": "V120 Restaurent og Lounge", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.544758, 55.671188] } },
        { "type": "Feature", "properties": { "name": "XOCOVINO", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5750784, 55.6799824] } },
        { "type": "Feature", "properties": { "name": "108 - The Corner", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5977751, 55.677653] } },
        { "type": "Feature", "properties": { "name": "Scrollbar", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.590689, 55.6593211] } },
        { "type": "Feature", "properties": { "name": "braincorp", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.57642, 55.69075] } },
        { "type": "Feature", "properties": { "name": "Jolene", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.56117, 55.66732] } },
        { "type": "Feature", "properties": { "name": "Mesteren & Lærlingen", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5589, 55.66769] } },
        { "type": "Feature", "properties": { "name": "", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5778012, 55.6386512] } },
        { "type": "Feature", "properties": { "name": "Boulebar Sankt Petri", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.571343, 55.680944] } },
        { "type": "Feature", "properties": { "name": "Helium", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5917684, 55.6864283] } },
        { "type": "Feature", "properties": { "name": "Aloë Cocktailbar", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5746002, 55.6777863] } },
        { "type": "Feature", "properties": { "name": "Bar 6", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5716911, 55.703247] } },
        { "type": "Feature", "properties": { "name": "Boulevarden", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5488293, 55.6654227] } },
        { "type": "Feature", "properties": { "name": "Kronborggade 3", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5446425, 55.6913826] } },
        { "type": "Feature", "properties": { "name": "Nimb Vinotek", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5660812, 55.6735206] } },
        { "type": "Feature", "properties": { "name": "Hotel Copenhagen Crown Bar", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5565779, 55.6723723] } },
        { "type": "Feature", "properties": { "name": "The Barbershop", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5879807, 55.6832898] } },
        { "type": "Feature", "properties": { "name": "The Globe", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5709215, 55.681795] } },
        { "type": "Feature", "properties": { "name": "Pasteur", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5767903, 55.6989423] } },
        { "type": "Feature", "properties": { "name": "Haabet Bodega Bar", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5972606, 55.6674267] } },
        { "type": "Feature", "properties": { "name": "Kompasset Ølbar", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5772166, 55.7095672] } },
        { "type": "Feature", "properties": { "name": "Chevy's", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5900305, 55.7037321] } },
        { "type": "Feature", "properties": { "name": "Fyret", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5899983, 55.7035356] } },
        { "type": "Feature", "properties": { "name": "Kant-bar", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.580105, 55.678721] } },
        { "type": "Feature", "properties": { "name": "Damsø cafe", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.4854659, 55.6849767] } },
        { "type": "Feature", "properties": { "name": "Jydepotten bodega", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.4908342, 55.686311] } },
        { "type": "Feature", "properties": { "name": "The Southern Cross Pub, Copenhagen", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.57242, 55.67524] } },
        { "type": "Feature", "properties": { "name": "Ancestrale", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5496708, 55.671211] } },
        { "type": "Feature", "properties": { "name": "Rbabarrab", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.55307, 55.6665209] } },
        { "type": "Feature", "properties": { "name": "The Bar 3.4", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.573264, 55.6253234] } },
        { "type": "Feature", "properties": { "name": "The Bar 1.6", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.573272, 55.6254657] } },
        { "type": "Feature", "properties": { "name": "The Bar 1.1", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5735999, 55.6256755] } },
        { "type": "Feature", "properties": { "name": "The Bar 0.3", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5734422, 55.6257302] } },
        { "type": "Feature", "properties": { "name": "The Bar 1.3", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5734046, 55.6256575] } },
        { "type": "Feature", "properties": { "name": "Absolut", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5731751, 55.624693] } },
        { "type": "Feature", "properties": { "name": "Nicolas Feuillatte Bar", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5736874, 55.6247868] } },
        { "type": "Feature", "properties": { "name": "The Bar 3.2", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5739759, 55.6256545] } },
        { "type": "Feature", "properties": { "name": "Dandy", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5875853, 55.683378] } },
        { "type": "Feature", "properties": { "name": "Kanalens Kælder", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5930274, 55.6758239] } },
        { "type": "Feature", "properties": { "name": "Toto Vin- og Spisebar", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.6098903, 55.6558235] } },
        { "type": "Feature", "properties": { "name": "Bageriet", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.567677, 55.692108] } },
        { "type": "Feature", "properties": { "name": "Haven Bar", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.592246, 55.6780124] } },
        { "type": "Feature", "properties": { "name": "Barvin", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5879149, 55.6742779] } },
        { "type": "Feature", "properties": { "name": "Osborne", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5595621, 55.6902991] } },
        { "type": "Feature", "properties": { "name": "The Ballroom Nr. 1", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5738749, 55.7025084] } },
        { "type": "Feature", "properties": { "name": "Peders - Pisserendens ølkælder", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5690251, 55.679078] } },
        { "type": "Feature", "properties": { "name": "Sabotøren", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5563343, 55.6960863] } },
        { "type": "Feature", "properties": { "name": "The Ballroom Nr. 2", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5737636, 55.7024713] } },
        { "type": "Feature", "properties": { "name": "Nordvest Ølbar", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5339291, 55.7065226] } },
        { "type": "Feature", "properties": { "name": "", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5346603, 55.7056895] } },
        { "type": "Feature", "properties": { "name": "Østerbros Perle", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5809356, 55.7012563] } },
        { "type": "Feature", "properties": { "name": "Mother Wine", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.580252, 55.6816] } },
        { "type": "Feature", "properties": { "name": "Miami", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5716769, 55.6782794] } },
        { "type": "Feature", "properties": { "name": "The Drunken Flamingo", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5718204, 55.6783238] } },
        { "type": "Feature", "properties": { "name": "Francis Pony", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.57495, 55.6793474] } },
        { "type": "Feature", "properties": { "name": "Farfar", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5748724, 55.6800374] } },
        { "type": "Feature", "properties": { "name": "Just a winebar", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.598651, 55.707977] } },
        { "type": "Feature", "properties": { "name": "Rhino Bar", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5711571, 55.6820368] } },
        { "type": "Feature", "properties": { "name": "Comedy Zoo Cafe", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5755872, 55.6770916] } },
        { "type": "Feature", "properties": { "name": "Zeppelin", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5558859, 55.6722464] } },
        { "type": "Feature", "properties": { "name": "Ålholm Borgerkro", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.4894709, 55.6707018] } },
        { "type": "Feature", "properties": { "name": "Kvali Bar", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.4840667, 55.6828585] } },
        { "type": "Feature", "properties": { "name": "Støvlen", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.4837107, 55.6919259] } },
        { "type": "Feature", "properties": { "name": "Husum Bodega", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.4768678, 55.7102686] } },
        { "type": "Feature", "properties": { "name": "Byens bodega", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5722551, 55.6714963] } },
        { "type": "Feature", "properties": { "name": "Søhesten", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5720729, 55.6903189] } },
        { "type": "Feature", "properties": { "name": "Teglværket", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5519385, 55.6536616] } },
        { "type": "Feature", "properties": { "name": "No Stress Bar DK", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5712927, 55.6814236] } },
        { "type": "Feature", "properties": { "name": "The reception", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.552406, 55.6717677] } },
        { "type": "Feature", "properties": { "name": "Cafe Strandlyst", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5768917, 55.7126998] } },
        { "type": "Feature", "properties": { "name": "Beviamo Winebar", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5836296, 55.7024109] } },
        { "type": "Feature", "properties": { "name": "Whammy Bar", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.6135641, 55.6655993] } },
        { "type": "Feature", "properties": { "name": "", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5533363, 55.6676668] } },
        { "type": "Feature", "properties": { "name": "BYOH Matcha Bar & Matcha Mike", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5613882, 55.6720221] } },
        { "type": "Feature", "properties": { "name": "Absalon Bar", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5617535, 55.6717046] } },
        { "type": "Feature", "properties": { "name": "Men\"s bar", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5684369, 55.6792622] } },
        { "type": "Feature", "properties": { "name": "Kiss Kiss Bear Bar", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5681405, 55.678001] } },
        { "type": "Feature", "properties": { "name": "Bootleggers", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5702644, 55.6835862] } },
        { "type": "Feature", "properties": { "name": "Halmtorvet 9", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5616796, 55.6704442] } },
        { "type": "Feature", "properties": { "name": "Copenhagen Marriott Excecutive Lounge", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.574102, 55.6687889] } },
        { "type": "Feature", "properties": { "name": "Honey rider cocktail lounge", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5729105, 55.6754177] } },
        { "type": "Feature", "properties": { "name": "Cph down town", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.574294, 55.6759648] } },
        { "type": "Feature", "properties": { "name": "Mikropolis", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5660949, 55.6851285] } },
        { "type": "Feature", "properties": { "name": "The Mirror", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5745925, 55.6778037] } },
        { "type": "Feature", "properties": { "name": "Slusen", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5421382, 55.6495603] } },
        { "type": "Feature", "properties": { "name": "Bar7", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5707675, 55.6789888] } },
        { "type": "Feature", "properties": { "name": "Fischers kro", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.513977, 55.691993] } },
        { "type": "Feature", "properties": { "name": "Amager Bryghus Taproom", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5728065, 55.6843297] } },
        { "type": "Feature", "properties": { "name": "Jazzhus Montmartre Bar", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.582499, 55.681984] } },
        { "type": "Feature", "properties": { "name": "Vinothek Marquart", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5789412, 55.6675846] } },
        { "type": "Feature", "properties": { "name": "Curfew", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5570465, 55.6728406] } },
        { "type": "Feature", "properties": { "name": "The Ugly Duckling Brewery", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5343114, 55.7062905] } },
        { "type": "Feature", "properties": { "name": "Voodoo Lounge", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5765266, 55.6794574] } },
        { "type": "Feature", "properties": { "name": "Beer and the Bean", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5785514, 55.6657426] } },
        { "type": "Feature", "properties": { "name": "Bicycle Brewing", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5793537, 55.7055585] } },
        { "type": "Feature", "properties": { "name": "FUGU", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5782539, 55.6776889] } },
        { "type": "Feature", "properties": { "name": "Escobar København", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5596058, 55.6877573] } },
        { "type": "Feature", "properties": { "name": "Bar Piccolo", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5842138, 55.6796922] } },
        { "type": "Feature", "properties": { "name": "Fräulein", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.543381, 55.671134] } },
        { "type": "Feature", "properties": { "name": "Bar Una", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5502065, 55.6679133] } },
        { "type": "Feature", "properties": { "name": "", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5584422, 55.7019255] } },
        { "type": "Feature", "properties": { "name": "Tipsy Mermaid", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5930626, 55.6785383] } },
        { "type": "Feature", "properties": { "name": "Mågekroen", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.527665, 55.702241] } },
        { "type": "Feature", "properties": { "name": "Cocktail Bar 1408", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5886895, 55.672168] } },
        { "type": "Feature", "properties": { "name": "Hop House", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.6103787, 55.6545487] } },
        { "type": "Feature", "properties": { "name": "1420", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5546848, 55.6886272] } },
        { "type": "Feature", "properties": { "name": "Skovbar", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5445454, 55.690773] } },
        { "type": "Feature", "properties": { "name": "Duck and Cover", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.552391, 55.671848] } },
        { "type": "Feature", "properties": { "name": "Klint & Bro", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5510359, 55.7012874] } },
        { "type": "Feature", "properties": { "name": "Malbeck Vinbar", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5152145, 55.6663641] } },
        { "type": "Feature", "properties": { "name": "Citizen Cocktailbar", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5857039, 55.6846756] } },
        { "type": "Feature", "properties": { "name": "Alfons Vinbar", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5576415, 55.6658081] } },
        { "type": "Feature", "properties": { "name": "Godt Øl", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5760433, 55.6768192] } },
        { "type": "Feature", "properties": { "name": "Y's Café og Cocktailbar", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5733801, 55.6839424] } },
        { "type": "Feature", "properties": { "name": "Tørst Bar", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.57013, 55.6775774] } },
        { "type": "Feature", "properties": { "name": "Beer hut", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5660747, 55.7310435] } },
        { "type": "Feature", "properties": { "name": "Vinøs Vinbar", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.6234122, 55.663505] } },
        { "type": "Feature", "properties": { "name": "Malbeck Valby", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.515379, 55.666374] } },
        { "type": "Feature", "properties": { "name": "Amazonia Cocktail and kitchen", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.559317, 55.687472] } },
        { "type": "Feature", "properties": { "name": "Bar Deco", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5837622, 55.6812174] } },
        { "type": "Feature", "properties": { "name": "Åbenbar", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.537079, 55.706478] } },
        { "type": "Feature", "properties": { "name": "Not your Usual", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5716401, 55.6762539] } },
        { "type": "Feature", "properties": { "name": "Scandic Sydhavn Bar", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5414745, 55.6545652] } },
        { "type": "Feature", "properties": { "name": "HIGH VOLTAGE", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5640869, 55.6755802] } },
        { "type": "Feature", "properties": { "name": "Kyros & Co.", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5680392, 55.6796526] } },
        { "type": "Feature", "properties": { "name": "Kødbyens Rosébar", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.55769, 55.6663814] } },
        { "type": "Feature", "properties": { "name": "Papa Bird", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5584464, 55.6666515] } },
        { "type": "Feature", "properties": { "name": "Sams Bar", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5703918, 55.6770384] } },
        { "type": "Feature", "properties": { "name": "FoxN Friends", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5727426, 55.684295] } },
        { "type": "Feature", "properties": { "name": "Fermentabel", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.574765, 55.6393649] } },
        { "type": "Feature", "properties": { "name": "Zefside", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5750111, 55.6758545] } },
        { "type": "Feature", "properties": { "name": "Ved Siden Af", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5670632, 55.6757775] } },
        { "type": "Feature", "properties": { "name": "Skicaféen", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.6185904, 55.6840995] } },
        { "type": "Feature", "properties": { "name": "Bip Bip Bar", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.559758, 55.6889032] } },
        { "type": "Feature", "properties": { "name": "Klovnens Bodega", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5440284, 55.688681] } },
        { "type": "Feature", "properties": { "name": "Puss Puss", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.580356, 55.678036] } },
        { "type": "Feature", "properties": { "name": "Glentekroen", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5354754, 55.6979088] } },
        { "type": "Feature", "properties": { "name": "Atze Peng", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5430459, 55.6657876] } },
        { "type": "Feature", "properties": { "name": "Nærvær", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5501541, 55.6728403] } },
        { "type": "Feature", "properties": { "name": "Café Dan Turell", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5817854, 55.6816096] } },
        { "type": "Feature", "properties": { "name": "TAPS Winebar Copenhagen", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.58271, 55.6818] } }
    ]
}
