export const kebab = {
    "type": "FeatureCollection",
    "name": "kebab",
    "crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
    "features": [
        { "type": "Feature", "properties": { "name": "Yilmaz Döner Kebab", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.526777, 55.7045707] } },
        { "type": "Feature", "properties": { "name": "King of Kebab", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5602562, 55.6881659] } },
        { "type": "Feature", "properties": { "name": "Divane Kebab", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5932027, 55.6712683] } },
        { "type": "Feature", "properties": { "name": "Shawarma Grillhouse", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5698547, 55.6767719] } },
        { "type": "Feature", "properties": { "name": "Amager Kebab 2001", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5985614, 55.6661025] } },
        { "type": "Feature", "properties": { "name": "Grill House Kebab", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5431166, 55.6976338] } },
        { "type": "Feature", "properties": { "name": "Dürüm Bar", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5442625, 55.6971827] } },
        { "type": "Feature", "properties": { "name": "Kösk Kebab", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5343864, 55.7014696] } },
        { "type": "Feature", "properties": { "name": "Pølse og Grill", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.4877403, 55.6537908] } },
        { "type": "Feature", "properties": { "name": "Konya Kebab", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.550713, 55.693296] } },
        { "type": "Feature", "properties": { "name": "Kösem", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.544475, 55.697354] } },
        { "type": "Feature", "properties": { "name": "Kebabistan", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5468544, 55.6957908] } },
        { "type": "Feature", "properties": { "name": "Kebab House", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.4811659, 55.7188166] } },
        { "type": "Feature", "properties": { "name": "Atlas Pizza Kebab", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5255659, 55.7086711] } },
        { "type": "Feature", "properties": { "name": "Elvan Shawarma", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5406505, 55.6995737] } },
        { "type": "Feature", "properties": { "name": "Falafel Huset", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5300552, 55.7032673] } },
        { "type": "Feature", "properties": { "name": "Flamingo Kebab", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5409205, 55.699372] } },
        { "type": "Feature", "properties": { "name": "Samosa House", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5324727, 55.7020249] } },
        { "type": "Feature", "properties": { "name": "Sultan", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5537053, 55.6912931] } },
        { "type": "Feature", "properties": { "name": "ZamZam Kebab", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5351261, 55.701644] } },
        { "type": "Feature", "properties": { "name": "Öz Konya Kebab", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5359403, 55.7014984] } },
        { "type": "Feature", "properties": { "name": "Amar Konya Kebab", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.6062006, 55.6592466] } },
        { "type": "Feature", "properties": { "name": "City Kebab", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.6075243, 55.6585095] } },
        { "type": "Feature", "properties": { "name": "Kebabland", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.601565, 55.662954] } },
        { "type": "Feature", "properties": { "name": "Vefa Kebab", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.58301, 55.702165] } },
        { "type": "Feature", "properties": { "name": "Silos", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5781443, 55.6986712] } },
        { "type": "Feature", "properties": { "name": "Kebabisan 4", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.606451, 55.658998] } },
        { "type": "Feature", "properties": { "name": "Mr. Shawarma", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5999269, 55.6728758] } },
        { "type": "Feature", "properties": { "name": "Husum Kebab", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.4782775, 55.7103981] } },
        { "type": "Feature", "properties": { "name": "Istanbul Kebab", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5479701, 55.7033449] } },
        { "type": "Feature", "properties": { "name": "Kebab Snedker", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.488369, 55.672225] } },
        { "type": "Feature", "properties": { "name": "Istanbul Kebab House", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5102099, 55.6943746] } },
        { "type": "Feature", "properties": { "name": "Zeit & Zaatar", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5550836, 55.6886465] } },
        { "type": "Feature", "properties": { "name": "Dünyam Shawarma House", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5478768, 55.6676897] } },
        { "type": "Feature", "properties": { "name": "Ankara Dürüm House", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.552411, 55.668736] } },
        { "type": "Feature", "properties": { "name": "Star Midnight Kebab & Grill", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5493432, 55.6678946] } },
        { "type": "Feature", "properties": { "name": "Liban Cuisine", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5529348, 55.685186] } },
        { "type": "Feature", "properties": { "name": "Kebab Palace", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5701356, 55.6769031] } },
        { "type": "Feature", "properties": { "name": "Ali Bageri", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5443468, 55.7029393] } },
        { "type": "Feature", "properties": { "name": "Fresh Kebab", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5349369, 55.7013819] } },
        { "type": "Feature", "properties": { "name": "Shawarma Palace", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5463653, 55.6958173] } },
        { "type": "Feature", "properties": { "name": "Brønshøj Kebab", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.4921195, 55.7056595] } },
        { "type": "Feature", "properties": { "name": "Silas Kebab", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.607869, 55.657823] } },
        { "type": "Feature", "properties": { "name": "Kebaben", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.582919, 55.6821813] } },
        { "type": "Feature", "properties": { "name": "Original Shawarma", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.570899, 55.6734063] } },
        { "type": "Feature", "properties": { "name": "Falafelboden Christiania", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5609391, 55.6690182] } },
        { "type": "Feature", "properties": { "name": "Smiley's Kebab", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.6030801, 55.6634208] } },
        { "type": "Feature", "properties": { "name": "Station Kebab", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5168221, 55.6524699] } },
        { "type": "Feature", "properties": { "name": "Sheiks Shawarma", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5514018, 55.6928381] } },
        { "type": "Feature", "properties": { "name": "Madam bum", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5393975, 55.6663328] } },
        { "type": "Feature", "properties": { "name": "KEBABBAR", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5496619, 55.6952899] } },
        { "type": "Feature", "properties": { "name": "Durum Bar Svanemøllen", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.577266, 55.715093] } },
        { "type": "Feature", "properties": { "name": "AbuSamra", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5480657, 55.7029259] } },
        { "type": "Feature", "properties": { "name": "Kebabhjørnet", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.483019, 55.661264] } },
        { "type": "Feature", "properties": { "name": "Mamati", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5160019, 55.6633138] } },
        { "type": "Feature", "properties": { "name": "Tadim Kebab", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.476658, 55.710557] } },
        { "type": "Feature", "properties": { "name": "Ørestad Kebab", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5795261, 55.6293433] } },
        { "type": "Feature", "properties": { "name": "Fuldkorn Kebab", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5473352, 55.6954671] } },
        { "type": "Feature", "properties": { "name": "SIMPLY", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.6226963, 55.6643031] } },
        { "type": "Feature", "properties": { "name": "Mahalle CPH", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5563529, 55.6893625] } },
        { "type": "Feature", "properties": { "name": "Bon Appétit", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5683225, 55.6780907] } },
        { "type": "Feature", "properties": { "name": "Le Bon Gout", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5132798, 55.6926331] } },
        { "type": "Feature", "properties": { "name": "Mahalle", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5583636, 55.6903015] } },
        { "type": "Feature", "properties": { "name": "Garbanzo", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5803808, 55.6810435] } },
        { "type": "Feature", "properties": { "name": "Super Kebab", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.474241, 55.711498] } },
        { "type": "Feature", "properties": { "name": "Stefanos pita guys", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5530819, 55.698336] } },
        { "type": "Feature", "properties": { "name": "Øst Kebab", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.577341, 55.7138375] } },
        { "type": "Feature", "properties": { "name": "MAK KEBAB", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5746676, 55.6900601] } },
        { "type": "Feature", "properties": { "name": "Kenzicph", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5326449, 55.7047811] } },
        { "type": "Feature", "properties": { "name": "Divane Kebab 2", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5931825, 55.6712929] } },
        { "type": "Feature", "properties": { "name": "Byens Grill Kebab", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.5014131, 55.6432168] } },
        { "type": "Feature", "properties": { "name": "Doner Kebab", "wikidata": "", "wikipedia": "" }, "geometry": { "type": "Point", "coordinates": [12.572885, 55.678166] } }
    ]
}
